name: Dockerize react applicaiton
on:
  push:
    branches: [ "main" ]
jobs:
  build-container:
    name: build docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to dockerhub
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: aliherawi7/portal-app:latest
          
      
